// Generated from https://api.fontsource.org/v1/fonts.
// Curated set: every Google Font that ships all four standard
// variants (Regular / Bold / Italic / Bold-Italic) in the Latin
// subset. The 3 "bundled: true" families load from public/fonts/
// (offline-capable); the rest fetch from the Fontsource jsDelivr
// CDN on first use and cache via the browser HTTP cache.
//
// To regenerate: re-run the dev script that pulls the API and
// writes this file (see plan in plans/shimmering-sprouting-lecun.md).

import type { FontFamilyEntry } from './textVector';

export const TEXT_FONT_FAMILIES: ReadonlyArray<FontFamilyEntry> = [
  { slug: 'inter', family: "Inter", category: 'sans-serif', bundled: true },
  { slug: 'lora', family: "Lora", category: 'serif', bundled: true },
  { slug: 'playfair-display', family: "Playfair Display", category: 'serif', bundled: true },
  { slug: 'advent-pro', family: "Advent Pro", category: 'sans-serif' },
  { slug: 'afacad', family: "Afacad", category: 'sans-serif' },
  { slug: 'albert-sans', family: "Albert Sans", category: 'sans-serif' },
  { slug: 'alegreya', family: "Alegreya", category: 'serif' },
  { slug: 'alegreya-sans', family: "Alegreya Sans", category: 'sans-serif' },
  { slug: 'alegreya-sans-sc', family: "Alegreya Sans SC", category: 'sans-serif' },
  { slug: 'alegreya-sc', family: "Alegreya SC", category: 'serif' },
  { slug: 'aleo', family: "Aleo", category: 'serif' },
  { slug: 'almendra', family: "Almendra", category: 'serif' },
  { slug: 'alumni-sans', family: "Alumni Sans", category: 'sans-serif' },
  { slug: 'alumni-sans-sc', family: "Alumni Sans SC", category: 'sans-serif' },
  { slug: 'amaranth', family: "Amaranth", category: 'sans-serif' },
  { slug: 'amarna', family: "Amarna", category: 'sans-serif' },
  { slug: 'amiri', family: "Amiri", category: 'serif' },
  { slug: 'ancizar-sans', family: "Ancizar Sans", category: 'sans-serif' },
  { slug: 'ancizar-serif', family: "Ancizar Serif", category: 'serif' },
  { slug: 'andada-pro', family: "Andada Pro", category: 'serif' },
  { slug: 'andika', family: "Andika", category: 'sans-serif' },
  { slug: 'anonymous-pro', family: "Anonymous Pro", category: 'monospace' },
  { slug: 'anybody', family: "Anybody", category: 'display' },
  { slug: 'archivo', family: "Archivo", category: 'sans-serif' },
  { slug: 'archivo-narrow', family: "Archivo Narrow", category: 'sans-serif' },
  { slug: 'arimo', family: "Arimo", category: 'sans-serif' },
  { slug: 'arsenal', family: "Arsenal", category: 'sans-serif' },
  { slug: 'arsenal-sc', family: "Arsenal SC", category: 'sans-serif' },
  { slug: 'arvo', family: "Arvo", category: 'serif' },
  { slug: 'asap', family: "Asap", category: 'sans-serif' },
  { slug: 'asap-condensed', family: "Asap Condensed", category: 'sans-serif' },
  { slug: 'atkinson-hyperlegible', family: "Atkinson Hyperlegible", category: 'sans-serif' },
  { slug: 'atkinson-hyperlegible-mono', family: "Atkinson Hyperlegible Mono", category: 'sans-serif' },
  { slug: 'atkinson-hyperlegible-next', family: "Atkinson Hyperlegible Next", category: 'sans-serif' },
  { slug: 'averia-libre', family: "Averia Libre", category: 'display' },
  { slug: 'averia-sans-libre', family: "Averia Sans Libre", category: 'display' },
  { slug: 'averia-serif-libre', family: "Averia Serif Libre", category: 'display' },
  { slug: 'azeret-mono', family: "Azeret Mono", category: 'monospace' },
  { slug: 'b612', family: "B612", category: 'sans-serif' },
  { slug: 'b612-mono', family: "B612 Mono", category: 'monospace' },
  { slug: 'bai-jamjuree', family: "Bai Jamjuree", category: 'sans-serif' },
  { slug: 'balsamiq-sans', family: "Balsamiq Sans", category: 'display' },
  { slug: 'barlow', family: "Barlow", category: 'sans-serif' },
  { slug: 'barlow-condensed', family: "Barlow Condensed", category: 'sans-serif' },
  { slug: 'barlow-semi-condensed', family: "Barlow Semi Condensed", category: 'sans-serif' },
  { slug: 'baskervville', family: "Baskervville", category: 'serif' },
  { slug: 'be-vietnam-pro', family: "Be Vietnam Pro", category: 'sans-serif' },
  { slug: 'bellota', family: "Bellota", category: 'display' },
  { slug: 'bellota-text', family: "Bellota Text", category: 'display' },
  { slug: 'besley', family: "Besley", category: 'serif' },
  { slug: 'bitter', family: "Bitter", category: 'serif' },
  { slug: 'bodoni-moda', family: "Bodoni Moda", category: 'serif' },
  { slug: 'bodoni-moda-sc', family: "Bodoni Moda SC", category: 'serif' },
  { slug: 'bona-nova', family: "Bona Nova", category: 'serif' },
  { slug: 'bona-nova-sc', family: "Bona Nova SC", category: 'serif' },
  { slug: 'brygada-1918', family: "Brygada 1918", category: 'serif' },
  { slug: 'cabin', family: "Cabin", category: 'sans-serif' },
  { slug: 'caladea', family: "Caladea", category: 'serif' },
  { slug: 'cambay', family: "Cambay", category: 'sans-serif' },
  { slug: 'cantarell', family: "Cantarell", category: 'sans-serif' },
  { slug: 'cardo', family: "Cardo", category: 'serif' },
  { slug: 'carlito', family: "Carlito", category: 'sans-serif' },
  { slug: 'cascadia-code', family: "Cascadia Code", category: 'sans-serif' },
  { slug: 'cascadia-mono', family: "Cascadia Mono", category: 'sans-serif' },
  { slug: 'caudex', family: "Caudex", category: 'serif' },
  { slug: 'chakra-petch', family: "Chakra Petch", category: 'sans-serif' },
  { slug: 'charis-sil', family: "Charis SIL", category: 'serif' },
  { slug: 'chiron-hei-hk', family: "Chiron Hei HK", category: 'sans-serif' },
  { slug: 'chiron-sung-hk', family: "Chiron Sung HK", category: 'serif' },
  { slug: 'chivo', family: "Chivo", category: 'sans-serif' },
  { slug: 'chivo-mono', family: "Chivo Mono", category: 'monospace' },
  { slug: 'comic-neue', family: "Comic Neue", category: 'handwriting' },
  { slug: 'cormorant', family: "Cormorant", category: 'serif' },
  { slug: 'cormorant-garamond', family: "Cormorant Garamond", category: 'serif' },
  { slug: 'cormorant-infant', family: "Cormorant Infant", category: 'serif' },
  { slug: 'courier-prime', family: "Courier Prime", category: 'monospace' },
  { slug: 'cousine', family: "Cousine", category: 'monospace' },
  { slug: 'crimson-pro', family: "Crimson Pro", category: 'serif' },
  { slug: 'crimson-text', family: "Crimson Text", category: 'serif' },
  { slug: 'cuprum', family: "Cuprum", category: 'sans-serif' },
  { slug: 'dai-banna-sil', family: "Dai Banna SIL", category: 'serif' },
  { slug: 'dm-sans', family: "DM Sans", category: 'sans-serif' },
  { slug: 'eb-garamond', family: "EB Garamond", category: 'serif' },
  { slug: 'economica', family: "Economica", category: 'sans-serif' },
  { slug: 'elms-sans', family: "Elms Sans", category: 'sans-serif' },
  { slug: 'epilogue', family: "Epilogue", category: 'sans-serif' },
  { slug: 'epunda-sans', family: "Epunda Sans", category: 'sans-serif' },
  { slug: 'epunda-slab', family: "Epunda Slab", category: 'serif' },
  { slug: 'exo', family: "Exo", category: 'sans-serif' },
  { slug: 'exo-2', family: "Exo 2", category: 'sans-serif' },
  { slug: 'expletus-sans', family: "Expletus Sans", category: 'display' },
  { slug: 'fahkwang', family: "Fahkwang", category: 'sans-serif' },
  { slug: 'familjen-grotesk', family: "Familjen Grotesk", category: 'sans-serif' },
  { slug: 'faustina', family: "Faustina", category: 'serif' },
  { slug: 'figtree', family: "Figtree", category: 'sans-serif' },
  { slug: 'finlandica', family: "Finlandica", category: 'sans-serif' },
  { slug: 'fira-sans', family: "Fira Sans", category: 'sans-serif' },
  { slug: 'fira-sans-condensed', family: "Fira Sans Condensed", category: 'sans-serif' },
  { slug: 'fira-sans-extra-condensed', family: "Fira Sans Extra Condensed", category: 'sans-serif' },
  { slug: 'fraunces', family: "Fraunces", category: 'serif' },
  { slug: 'funnel-sans', family: "Funnel Sans", category: 'sans-serif' },
  { slug: 'gantari', family: "Gantari", category: 'sans-serif' },
  { slug: 'gelasio', family: "Gelasio", category: 'serif' },
  { slug: 'genos', family: "Genos", category: 'sans-serif' },
  { slug: 'gentium-book-basic', family: "Gentium Book Basic", category: 'serif' },
  { slug: 'gentium-book-plus', family: "Gentium Book Plus", category: 'serif' },
  { slug: 'gentium-plus', family: "Gentium Plus", category: 'serif' },
  { slug: 'geom', family: "Geom", category: 'sans-serif' },
  { slug: 'georama', family: "Georama", category: 'sans-serif' },
  { slug: 'gfs-neohellenic', family: "GFS Neohellenic", category: 'sans-serif' },
  { slug: 'glory', family: "Glory", category: 'sans-serif' },
  { slug: 'google-sans', family: "Google Sans", category: 'sans-serif' },
  { slug: 'google-sans-code', family: "Google Sans Code", category: 'monospace' },
  { slug: 'grandstander', family: "Grandstander", category: 'display' },
  { slug: 'grenze', family: "Grenze", category: 'serif' },
  { slug: 'gudea', family: "Gudea", category: 'sans-serif' },
  { slug: 'hanken-grotesk', family: "Hanken Grotesk", category: 'sans-serif' },
  { slug: 'host-grotesk', family: "Host Grotesk", category: 'sans-serif' },
  { slug: 'hubot-sans', family: "Hubot Sans", category: 'sans-serif' },
  { slug: 'ibarra-real-nova', family: "Ibarra Real Nova", category: 'serif' },
  { slug: 'ibm-plex-mono', family: "IBM Plex Mono", category: 'monospace' },
  { slug: 'ibm-plex-sans', family: "IBM Plex Sans", category: 'sans-serif' },
  { slug: 'ibm-plex-sans-condensed', family: "IBM Plex Sans Condensed", category: 'sans-serif' },
  { slug: 'ibm-plex-serif', family: "IBM Plex Serif", category: 'serif' },
  { slug: 'inclusive-sans', family: "Inclusive Sans", category: 'sans-serif' },
  { slug: 'inria-sans', family: "Inria Sans", category: 'sans-serif' },
  { slug: 'inria-serif', family: "Inria Serif", category: 'serif' },
  { slug: 'instrument-sans', family: "Instrument Sans", category: 'sans-serif' },
  { slug: 'intel-one-mono', family: "Intel One Mono", category: 'monospace' },
  { slug: 'inter-tight', family: "Inter Tight", category: 'sans-serif' },
  { slug: 'iosevka-charon', family: "Iosevka Charon", category: 'monospace' },
  { slug: 'iosevka-charon-mono', family: "Iosevka Charon Mono", category: 'monospace' },
  { slug: 'istok-web', family: "Istok Web", category: 'sans-serif' },
  { slug: 'jetbrains-mono', family: "JetBrains Mono", category: 'monospace' },
  { slug: 'josefin-sans', family: "Josefin Sans", category: 'sans-serif' },
  { slug: 'josefin-slab', family: "Josefin Slab", category: 'serif' },
  { slug: 'jost', family: "Jost", category: 'sans-serif' },
  { slug: 'judson', family: "Judson", category: 'serif' },
  { slug: 'k2d', family: "K2D", category: 'sans-serif' },
  { slug: 'kanit', family: "Kanit", category: 'sans-serif' },
  { slug: 'kantumruy-pro', family: "Kantumruy Pro", category: 'sans-serif' },
  { slug: 'karla', family: "Karla", category: 'sans-serif' },
  { slug: 'kodchasan', family: "Kodchasan", category: 'sans-serif' },
  { slug: 'koho', family: "KoHo", category: 'sans-serif' },
  { slug: 'krub', family: "Krub", category: 'sans-serif' },
  { slug: 'kufam', family: "Kufam", category: 'sans-serif' },
  { slug: 'kulim-park', family: "Kulim Park", category: 'sans-serif' },
  { slug: 'labrada', family: "Labrada", category: 'serif' },
  { slug: 'lato', family: "Lato", category: 'sans-serif' },
  { slug: 'lekton', family: "Lekton", category: 'monospace' },
  { slug: 'libertinus-sans', family: "Libertinus Sans", category: 'sans-serif' },
  { slug: 'libertinus-serif', family: "Libertinus Serif", category: 'serif' },
  { slug: 'libre-baskerville', family: "Libre Baskerville", category: 'serif' },
  { slug: 'libre-bodoni', family: "Libre Bodoni", category: 'serif' },
  { slug: 'libre-caslon-text', family: "Libre Caslon Text", category: 'serif' },
  { slug: 'libre-franklin', family: "Libre Franklin", category: 'sans-serif' },
  { slug: 'lilex', family: "Lilex", category: 'monospace' },
  { slug: 'lisu-bosa', family: "Lisu Bosa", category: 'serif' },
  { slug: 'literata', family: "Literata", category: 'serif' },
  { slug: 'livvic', family: "Livvic", category: 'sans-serif' },
  { slug: 'lobster-two', family: "Lobster Two", category: 'display' },
  { slug: 'mali', family: "Mali", category: 'handwriting' },
  { slug: 'manuale', family: "Manuale", category: 'serif' },
  { slug: 'marvel', family: "Marvel", category: 'sans-serif' },
  { slug: 'merriweather', family: "Merriweather", category: 'serif' },
  { slug: 'merriweather-sans', family: "Merriweather Sans", category: 'sans-serif' },
  { slug: 'miranda-sans', family: "Miranda Sans", category: 'sans-serif' },
  { slug: 'mohave', family: "Mohave", category: 'sans-serif' },
  { slug: 'mona-sans', family: "Mona Sans", category: 'sans-serif' },
  { slug: 'montserrat', family: "Montserrat", category: 'sans-serif' },
  { slug: 'montserrat-alternates', family: "Montserrat Alternates", category: 'sans-serif' },
  { slug: 'montserrat-underline', family: "Montserrat Underline", category: 'sans-serif' },
  { slug: 'mulish', family: "Mulish", category: 'sans-serif' },
  { slug: 'museomoderno', family: "MuseoModerno", category: 'display' },
  { slug: 'neuton', family: "Neuton", category: 'serif' },
  { slug: 'newsreader', family: "Newsreader", category: 'serif' },
  { slug: 'niramit', family: "Niramit", category: 'sans-serif' },
  { slug: 'nobile', family: "Nobile", category: 'sans-serif' },
  { slug: 'noticia-text', family: "Noticia Text", category: 'serif' },
  { slug: 'noto-sans', family: "Noto Sans", category: 'sans-serif' },
  { slug: 'noto-sans-display', family: "Noto Sans Display", category: 'sans-serif' },
  { slug: 'noto-serif', family: "Noto Serif", category: 'serif' },
  { slug: 'noto-serif-display', family: "Noto Serif Display", category: 'serif' },
  { slug: 'noto-serif-tamil', family: "Noto Serif Tamil", category: 'serif' },
  { slug: 'nunito', family: "Nunito", category: 'sans-serif' },
  { slug: 'nunito-sans', family: "Nunito Sans", category: 'sans-serif' },
  { slug: 'old-standard-tt', family: "Old Standard TT", category: 'serif' },
  { slug: 'open-sans', family: "Open Sans", category: 'sans-serif' },
  { slug: 'overlock', family: "Overlock", category: 'display' },
  { slug: 'overpass', family: "Overpass", category: 'sans-serif' },
  { slug: 'pathway-extreme', family: "Pathway Extreme", category: 'sans-serif' },
  { slug: 'petrona', family: "Petrona", category: 'serif' },
  { slug: 'philosopher', family: "Philosopher", category: 'sans-serif' },
  { slug: 'piazzolla', family: "Piazzolla", category: 'serif' },
  { slug: 'platypi', family: "Platypi", category: 'serif' },
  { slug: 'playfair', family: "Playfair", category: 'serif' },
  { slug: 'playfair-display-sc', family: "Playfair Display SC", category: 'serif' },
  { slug: 'plus-jakarta-sans', family: "Plus Jakarta Sans", category: 'sans-serif' },
  { slug: 'poltawski-nowy', family: "Poltawski Nowy", category: 'serif' },
  { slug: 'poppins', family: "Poppins", category: 'sans-serif' },
  { slug: 'prompt', family: "Prompt", category: 'sans-serif' },
  { slug: 'proza-libre', family: "Proza Libre", category: 'sans-serif' },
  { slug: 'pt-sans', family: "PT Sans", category: 'sans-serif' },
  { slug: 'pt-serif', family: "PT Serif", category: 'serif' },
  { slug: 'public-sans', family: "Public Sans", category: 'sans-serif' },
  { slug: 'puritan', family: "Puritan", category: 'sans-serif' },
  { slug: 'quantico', family: "Quantico", category: 'sans-serif' },
  { slug: 'quattrocento-sans', family: "Quattrocento Sans", category: 'sans-serif' },
  { slug: 'radio-canada', family: "Radio Canada", category: 'sans-serif' },
  { slug: 'radio-canada-big', family: "Radio Canada Big", category: 'sans-serif' },
  { slug: 'raleway', family: "Raleway", category: 'sans-serif' },
  { slug: 'rambla', family: "Rambla", category: 'sans-serif' },
  { slug: 'rasa', family: "Rasa", category: 'serif' },
  { slug: 'red-hat-display', family: "Red Hat Display", category: 'sans-serif' },
  { slug: 'red-hat-mono', family: "Red Hat Mono", category: 'monospace' },
  { slug: 'red-hat-text', family: "Red Hat Text", category: 'sans-serif' },
  { slug: 'reddit-sans', family: "Reddit Sans", category: 'sans-serif' },
  { slug: 'rem', family: "REM", category: 'sans-serif' },
  { slug: 'rethink-sans', family: "Rethink Sans", category: 'sans-serif' },
  { slug: 'roboto', family: "Roboto", category: 'sans-serif' },
  { slug: 'roboto-condensed', family: "Roboto Condensed", category: 'sans-serif' },
  { slug: 'roboto-mono', family: "Roboto Mono", category: 'monospace' },
  { slug: 'roboto-serif', family: "Roboto Serif", category: 'serif' },
  { slug: 'rokkitt', family: "Rokkitt", category: 'serif' },
  { slug: 'rosario', family: "Rosario", category: 'sans-serif' },
  { slug: 'rubik', family: "Rubik", category: 'sans-serif' },
  { slug: 'saira', family: "Saira", category: 'sans-serif' },
  { slug: 'saira-stencil', family: "Saira Stencil", category: 'display' },
  { slug: 'sansation', family: "Sansation", category: 'sans-serif' },
  { slug: 'sansita', family: "Sansita", category: 'sans-serif' },
  { slug: 'sarabun', family: "Sarabun", category: 'sans-serif' },
  { slug: 'savate', family: "Savate", category: 'sans-serif' },
  { slug: 'scada', family: "Scada", category: 'sans-serif' },
  { slug: 'schibsted-grotesk', family: "Schibsted Grotesk", category: 'sans-serif' },
  { slug: 'shantell-sans', family: "Shantell Sans", category: 'display' },
  { slug: 'share', family: "Share", category: 'sans-serif' },
  { slug: 'sn-pro', family: "SN Pro", category: 'sans-serif' },
  { slug: 'sofia-sans', family: "Sofia Sans", category: 'sans-serif' },
  { slug: 'sofia-sans-condensed', family: "Sofia Sans Condensed", category: 'sans-serif' },
  { slug: 'sofia-sans-extra-condensed', family: "Sofia Sans Extra Condensed", category: 'sans-serif' },
  { slug: 'sofia-sans-semi-condensed', family: "Sofia Sans Semi Condensed", category: 'sans-serif' },
  { slug: 'sometype-mono', family: "Sometype Mono", category: 'monospace' },
  { slug: 'sour-gummy', family: "Sour Gummy", category: 'sans-serif' },
  { slug: 'source-code-pro', family: "Source Code Pro", category: 'monospace' },
  { slug: 'source-sans-3', family: "Source Sans 3", category: 'sans-serif' },
  { slug: 'source-sans-pro', family: "Source Sans Pro", category: 'sans-serif' },
  { slug: 'source-serif-4', family: "Source Serif 4", category: 'serif' },
  { slug: 'source-serif-pro', family: "Source Serif Pro", category: 'serif' },
  { slug: 'space-mono', family: "Space Mono", category: 'monospace' },
  { slug: 'spectral', family: "Spectral", category: 'serif' },
  { slug: 'spectral-sc', family: "Spectral SC", category: 'serif' },
  { slug: 'spline-sans-mono', family: "Spline Sans Mono", category: 'monospace' },
  { slug: 'stix-two-text', family: "STIX Two Text", category: 'serif' },
  { slug: 'suse', family: "SUSE", category: 'sans-serif' },
  { slug: 'suse-mono', family: "SUSE Mono", category: 'sans-serif' },
  { slug: 'taviraj', family: "Taviraj", category: 'serif' },
  { slug: 'teachers', family: "Teachers", category: 'sans-serif' },
  { slug: 'texturina', family: "Texturina", category: 'serif' },
  { slug: 'thasadith', family: "Thasadith", category: 'sans-serif' },
  { slug: 'tinos', family: "Tinos", category: 'serif' },
  { slug: 'titillium-web', family: "Titillium Web", category: 'sans-serif' },
  { slug: 'tomorrow', family: "Tomorrow", category: 'sans-serif' },
  { slug: 'tourney', family: "Tourney", category: 'display' },
  { slug: 'trirong', family: "Trirong", category: 'serif' },
  { slug: 'trochut', family: "Trochut", category: 'display' },
  { slug: 'tuffy', family: "Tuffy", category: 'sans-serif' },
  { slug: 'ubuntu', family: "Ubuntu", category: 'sans-serif' },
  { slug: 'ubuntu-mono', family: "Ubuntu Mono", category: 'monospace' },
  { slug: 'ubuntu-sans', family: "Ubuntu Sans", category: 'sans-serif' },
  { slug: 'ubuntu-sans-mono', family: "Ubuntu Sans Mono", category: 'monospace' },
  { slug: 'unna', family: "Unna", category: 'serif' },
  { slug: 'urbanist', family: "Urbanist", category: 'sans-serif' },
  { slug: 'vend-sans', family: "Vend Sans", category: 'sans-serif' },
  { slug: 'victor-mono', family: "Victor Mono", category: 'monospace' },
  { slug: 'volkhov', family: "Volkhov", category: 'serif' },
  { slug: 'vollkorn', family: "Vollkorn", category: 'serif' },
  { slug: 'winky-rough', family: "Winky Rough", category: 'sans-serif' },
  { slug: 'winky-sans', family: "Winky Sans", category: 'sans-serif' },
  { slug: 'wittgenstein', family: "Wittgenstein", category: 'serif' },
  { slug: 'wix-madefor-text', family: "Wix Madefor Text", category: 'sans-serif' },
  { slug: 'work-sans', family: "Work Sans", category: 'sans-serif' },
  { slug: 'yrsa', family: "Yrsa", category: 'serif' },
  { slug: 'ysabeau', family: "Ysabeau", category: 'sans-serif' },
  { slug: 'ysabeau-infant', family: "Ysabeau Infant", category: 'sans-serif' },
  { slug: 'ysabeau-office', family: "Ysabeau Office", category: 'sans-serif' },
  { slug: 'zain', family: "Zain", category: 'sans-serif' },
  { slug: 'zalando-sans', family: "Zalando Sans", category: 'sans-serif' },
  { slug: 'zalando-sans-expanded', family: "Zalando Sans Expanded", category: 'sans-serif' },
  { slug: 'zalando-sans-semiexpanded', family: "Zalando Sans SemiExpanded", category: 'sans-serif' },
  { slug: 'zilla-slab', family: "Zilla Slab", category: 'serif' },
];
