import type { Layer, VectorData } from '@/types';
import { combineLayers } from './svgLayers';
import { computeTrimmedViewBox } from './trimSvg';

// ---------------------------------------------------------------------------
// Color utilities
// ---------------------------------------------------------------------------

const NAMED_COLORS: Record<string, string> = {
  black: '#000000', red: '#ff0000', green: '#008000', blue: '#0000ff',
  yellow: '#ffff00', cyan: '#00ffff', magenta: '#ff00ff', orange: '#ffa500',
  purple: '#800080', brown: '#a52a2a', gray: '#808080', grey: '#808080',
  pink: '#ffc0cb', lime: '#00ff00', navy: '#000080', teal: '#008080',
  maroon: '#800000', olive: '#808000', silver: '#c0c0c0',
};

/** Normalize any CSS color string to lowercase #rrggbb, or null for white/none. */
function normalizeHex(color: string): string | null {
  const c = color.trim().toLowerCase();
  if (!c || c === 'none' || c === 'transparent') return null;
  if (c === 'white' || c === '#fff' || c === '#ffffff') return null;
  if (c in NAMED_COLORS) {
    return NAMED_COLORS[c] === '#ffffff' ? null : NAMED_COLORS[c];
  }
  if (c.startsWith('#')) {
    if (c.length === 4) return '#' + c[1]+c[1]+c[2]+c[2]+c[3]+c[3];
    if (c.length === 7) return c;
    return null;
  }
  const rgb = c.match(/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/);
  if (rgb) {
    return '#' +
      parseInt(rgb[1]).toString(16).padStart(2, '0') +
      parseInt(rgb[2]).toString(16).padStart(2, '0') +
      parseInt(rgb[3]).toString(16).padStart(2, '0');
  }
  return null;
}

function isNearWhite(hex: string): boolean {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return 0.299 * r + 0.587 * g + 0.114 * b > 220;
}

/** Inline-style fill (for SVG style="fill: ..."). */
function styleFill(el: Element): string | null {
  const m = (el.getAttribute('style') ?? '').match(/(?:^|;)\s*fill:\s*([^;]+)/i);
  return m ? m[1].trim() : null;
}

/**
 * Parse all <style> elements in the SVG and extract simple class→fill mappings.
 * Handles the common Illustrator/Inkscape pattern of `.clsName { fill: red; }`.
 *
 * Limitations: only single-class selectors are recognized — a rule like
 * `.a, .b { fill: red }` only attributes the fill to `.b`. ID selectors and
 * compound selectors are not handled. This covers the typical autogenerated
 * output; complex hand-authored CSS would need a real CSS parser.
 */
function parseClassFills(svgRoot: SVGSVGElement): Map<string, string> {
  const map = new Map<string, string>();
  svgRoot.querySelectorAll('style').forEach(styleEl => {
    const text = (styleEl.textContent ?? '').replace(/\/\*[\s\S]*?\*\//g, ''); // strip comments
    const ruleRegex = /\.([\w-]+)\s*\{([^}]*)\}/g;
    let m: RegExpExecArray | null;
    while ((m = ruleRegex.exec(text)) !== null) {
      const cls = m[1];
      const body = m[2];
      const fillMatch = body.match(/(?:^|[;{\s])fill\s*:\s*([^;}]+)/i);
      if (fillMatch) map.set(cls, fillMatch[1].trim());
    }
  });
  return map;
}

/**
 * Resolve the effective fill color for an SVG element, walking up ancestors.
 * Order matches CSS specificity: inline style > class rule > fill attribute.
 */
function resolveFill(el: Element, classFills: Map<string, string>): string | null {
  let cur: Element | null = el;
  while (cur) {
    // 1. Inline style="fill:..." (highest specificity)
    const styled = styleFill(cur);
    if (styled) return styled;
    // 2. CSS class rule from <style> in <defs>
    const classAttr = cur.getAttribute('class');
    if (classAttr) {
      for (const c of classAttr.split(/\s+/)) {
        const f = classFills.get(c);
        if (f) return f;
      }
    }
    // 3. fill="..." presentation attribute (lowest CSS specificity)
    const direct = cur.getAttribute('fill');
    if (direct) return direct;
    cur = cur.parentElement;
  }
  return null;
}

// ---------------------------------------------------------------------------
// SVG → per-layer split
// ---------------------------------------------------------------------------

/** Collect leaf renderable elements (those that produce visible geometry). */
const RENDERABLE_TAGS = new Set([
  'path', 'rect', 'circle', 'ellipse', 'polygon', 'polyline', 'line',
]);

/**
 * Strip any `fill: ...` declaration from a CSS style string. We re-apply fill
 * explicitly via an attribute so the cloned leaf doesn't carry a fill that
 * came from an ancestor we're not re-emitting.
 */
function stripFillFromStyle(style: string): string {
  return style
    .split(';')
    .map(s => s.trim())
    .filter(s => s && !/^fill\s*:/i.test(s))
    .join('; ');
}

function splitSvgIntoLayers(svgRoot: SVGSVGElement): { layers: Layer[]; order: string[] } {
  const classFills = parseClassFills(svgRoot);
  const buckets = new Map<string, string[]>();
  const order: string[] = [];

  svgRoot.querySelectorAll('*').forEach(el => {
    if (!RENDERABLE_TAGS.has(el.tagName.toLowerCase())) return;
    const raw = resolveFill(el, classFills);
    if (!raw) return;
    const hex = normalizeHex(raw);
    if (!hex || isNearWhite(hex)) return;

    if (!buckets.has(hex)) {
      buckets.set(hex, []);
      order.push(hex);
    }

    // Clone and force the fill explicitly. We may emit this leaf without its
    // original ancestor chain, so any inherited fill must be baked in here.
    const clone = el.cloneNode(true) as Element;
    const inlineStyle = clone.getAttribute('style');
    if (inlineStyle) {
      const cleaned = stripFillFromStyle(inlineStyle);
      if (cleaned) clone.setAttribute('style', cleaned);
      else clone.removeAttribute('style');
    }
    clone.setAttribute('fill', hex);

    // Collect ancestor transforms (outermost → innermost) so the leaf renders
    // in the same coordinate system as in the original SVG. Authors commonly
    // wrap content in <g transform="matrix(...)"> (Inkscape layer transforms,
    // Illustrator artboard transforms, etc.) — losing these rotates/scales
    // /translates the entire piece.
    const ancestorTransforms: string[] = [];
    let cur: Element | null = el.parentElement;
    while (cur && cur !== svgRoot) {
      const t = cur.getAttribute('transform');
      if (t) ancestorTransforms.unshift(t);
      cur = cur.parentElement;
    }

    let html = clone.outerHTML;
    for (let i = ancestorTransforms.length - 1; i >= 0; i--) {
      html = `<g transform="${ancestorTransforms[i]}">${html}</g>`;
    }
    buckets.get(hex)!.push(html);
  });

  const layers: Layer[] = order.map(colorHex => ({
    colorHex,
    svgFragment: buckets.get(colorHex)!.join('\n'),
  }));

  return { layers, order };
}

// ---------------------------------------------------------------------------
// SVG
// ---------------------------------------------------------------------------

export async function parseSvg(file: File): Promise<VectorData> {
  const text = await file.text();
  const parser = new DOMParser();
  const doc = parser.parseFromString(text, 'image/svg+xml');
  const svgEl = doc.documentElement as unknown as SVGSVGElement;

  const vb = svgEl.getAttribute('viewBox');
  let w = 0, h = 0;
  if (vb) {
    const parts = vb.trim().split(/[\s,]+/).map(Number);
    w = parts[2];
    h = parts[3];
  }
  if (!w) w = parseFloat(svgEl.getAttribute('width') ?? '0');
  if (!h) h = parseFloat(svgEl.getAttribute('height') ?? '0');
  if (!w) w = 500;
  if (!h) h = 500;

  const viewBoxOriginal = vb ?? `0 0 ${w} ${h}`;
  const { layers, order } = splitSvgIntoLayers(svgEl);

  // Trim away whitespace around the actual content. The original layer
  // fragments are kept; the viewBox window selects only the content area.
  const initialSvg = combineLayers(layers, viewBoxOriginal, w, h);
  const trimmed = await computeTrimmedViewBox(initialSvg, w, h);

  return {
    svgString: combineLayers(layers, trimmed.viewBox, trimmed.naturalWidth, trimmed.naturalHeight),
    layers,
    naturalWidth: trimmed.naturalWidth,
    naturalHeight: trimmed.naturalHeight,
    viewBox: trimmed.viewBox,
    fileName: file.name,
    fileType: 'svg',
    detectedColors: order,
  };
}

// ---------------------------------------------------------------------------
// ACI (AutoCAD Color Index) → hex
// ---------------------------------------------------------------------------

const ACI_TABLE: Record<number, string> = {
  0: '#000000',  // ByBlock
  1: '#ff0000', 2: '#ffff00', 3: '#00ff00',
  4: '#00ffff', 5: '#0000ff', 6: '#ff00ff',
  7: '#000000',  // White in ACI → render as black
  8: '#414141', 9: '#808080',
  256: '#000000', // ByLayer → default black
};

function hslToHex(h: number, s: number, l: number): string {
  s /= 100; l /= 100;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => {
    const k = (n + h / 30) % 12;
    return Math.round(255 * (l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1)))
      .toString(16).padStart(2, '0');
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

function aciToHex(aci: number): string {
  if (aci in ACI_TABLE) return ACI_TABLE[aci];
  // ACI 10-249: 24 hue groups of 10 shades each
  const hue = Math.floor(((aci - 10) / 10) % 24) * 15;
  const shade = (aci - 10) % 10;
  const lightness = 50 - shade * 3;
  return hslToHex(hue, 90, Math.max(20, lightness));
}

// ---------------------------------------------------------------------------
// DXF → per-layer SVG fragments
// ---------------------------------------------------------------------------

interface DxfVertex { x: number; y: number; bulge?: number }

function bulgeToArc(
  x1: number, y1: number,
  x2: number, y2: number,
  bulge: number
): string {
  const b = bulge;
  const dx = x2 - x1, dy = y2 - y1;
  const len = Math.sqrt(dx * dx + dy * dy);
  const d = len / 2;
  const r = Math.abs((d * (1 + b * b)) / (2 * b));
  const largeArc = Math.abs(b) > 1 ? 1 : 0;
  const sweep = b > 0 ? 0 : 1;
  return `A ${r} ${r} 0 ${largeArc} ${sweep} ${x2} ${y2}`;
}

interface DxfEntity { type: string; colorHex?: string }
interface DxfLine extends DxfEntity { vertices: DxfVertex[] }
interface DxfPolyline extends DxfEntity { vertices: DxfVertex[]; shape?: boolean }
interface DxfCircle extends DxfEntity { center: DxfVertex; radius: number }
interface DxfArc extends DxfEntity { center: DxfVertex; radius: number; startAngle: number; endAngle: number }
interface DxfSpline extends DxfEntity { controlPoints: DxfVertex[]; closed?: boolean }
interface Bounds { minX: number; maxX: number; minY: number; maxY: number }

/** Render a single DXF entity to an SVG element string. Returns "" for unsupported types. */
function entityToSvg(e: DxfEntity, bounds: Bounds, strokeW: number): string {
  const color = e.colorHex ?? '#000000';
  const tx = (x: number) => x - bounds.minX;
  const ty = (y: number) => bounds.maxY - y;

  if (e.type === 'LINE') {
    const v = e as DxfLine;
    return `<line x1="${tx(v.vertices[0].x)}" y1="${ty(v.vertices[0].y)}" x2="${tx(v.vertices[1].x)}" y2="${ty(v.vertices[1].y)}" fill="none" stroke="${color}" stroke-width="${strokeW}" />`;
  }
  if (e.type === 'LWPOLYLINE' || e.type === 'POLYLINE') {
    const p = e as DxfPolyline;
    if (!p.vertices || p.vertices.length < 2) return '';
    const verts = p.vertices;
    let d = `M ${tx(verts[0].x)} ${ty(verts[0].y)}`;
    for (let i = 1; i < verts.length; i++) {
      const prev = verts[i - 1], curr = verts[i];
      const bulge = prev.bulge ?? 0;
      d += Math.abs(bulge) < 1e-6
        ? ` L ${tx(curr.x)} ${ty(curr.y)}`
        : ` ${bulgeToArc(tx(prev.x), ty(prev.y), tx(curr.x), ty(curr.y), -bulge)}`;
    }
    if (p.shape) {
      const last = verts[verts.length - 1], first = verts[0];
      const bulge = last.bulge ?? 0;
      d += Math.abs(bulge) < 1e-6
        ? ' Z'
        : ` ${bulgeToArc(tx(last.x), ty(last.y), tx(first.x), ty(first.y), -bulge)} Z`;
      return `<path d="${d}" fill="${color}" stroke="none" />`;
    }
    return `<path d="${d}" fill="none" stroke="${color}" stroke-width="${strokeW}" />`;
  }
  if (e.type === 'CIRCLE') {
    const c = e as DxfCircle;
    return `<circle cx="${tx(c.center.x)}" cy="${ty(c.center.y)}" r="${c.radius}" fill="${color}" stroke="none" />`;
  }
  if (e.type === 'ARC') {
    const a = e as DxfArc;
    const startRad = (a.startAngle * Math.PI) / 180;
    const endRad = (a.endAngle * Math.PI) / 180;
    const x1 = tx(a.center.x) + a.radius * Math.cos(startRad);
    const y1 = ty(a.center.y) - a.radius * Math.sin(startRad);
    const x2 = tx(a.center.x) + a.radius * Math.cos(endRad);
    const y2 = ty(a.center.y) - a.radius * Math.sin(endRad);
    const angleDiff = a.endAngle > a.startAngle ? a.endAngle - a.startAngle : 360 - a.startAngle + a.endAngle;
    const largeArc = angleDiff > 180 ? 1 : 0;
    const sweep = a.endAngle > a.startAngle ? 1 : 0;
    return `<path d="M ${x1} ${y1} A ${a.radius} ${a.radius} 0 ${largeArc} ${sweep} ${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${strokeW}" />`;
  }
  if (e.type === 'SPLINE') {
    const s = e as DxfSpline;
    if (!s.controlPoints || s.controlPoints.length < 2) return '';
    const pts = s.controlPoints;
    let d = `M ${tx(pts[0].x)} ${ty(pts[0].y)}`;
    for (let i = 1; i < pts.length; i++) d += ` L ${tx(pts[i].x)} ${ty(pts[i].y)}`;
    if (s.closed) {
      d += ' Z';
      return `<path d="${d}" fill="${color}" stroke="none" />`;
    }
    return `<path d="${d}" fill="none" stroke="${color}" stroke-width="${strokeW}" />`;
  }
  return '';
}

function computeBounds(entities: DxfEntity[]): Bounds {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  const sample = (x: number, y: number) => {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  };
  for (const e of entities) {
    if (e.type === 'LINE') {
      (e as DxfLine).vertices.forEach(v => sample(v.x, v.y));
    } else if (e.type === 'LWPOLYLINE' || e.type === 'POLYLINE') {
      (e as DxfPolyline).vertices?.forEach(v => sample(v.x, v.y));
    } else if (e.type === 'CIRCLE') {
      const c = e as DxfCircle;
      sample(c.center.x - c.radius, c.center.y - c.radius);
      sample(c.center.x + c.radius, c.center.y + c.radius);
    } else if (e.type === 'ARC') {
      const a = e as DxfArc;
      sample(a.center.x - a.radius, a.center.y - a.radius);
      sample(a.center.x + a.radius, a.center.y + a.radius);
    } else if (e.type === 'SPLINE') {
      (e as DxfSpline).controlPoints?.forEach(v => sample(v.x, v.y));
    }
  }
  if (!isFinite(minX)) { minX = 0; maxX = 1; minY = 0; maxY = 1; }
  return { minX, maxX, minY, maxY };
}

export async function parseDxf(file: File): Promise<VectorData> {
  const text = await file.text();

  const { default: DxfParser } = await import('dxf-parser');
  const parser = new DxfParser();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const dxf: any = parser.parseSync(text);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const resolveColor = (e: any): string | undefined => {
    if (typeof e.colorNumber === 'number' && e.colorNumber !== 256) {
      return aciToHex(e.colorNumber);
    }
    return undefined;
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const entities: DxfEntity[] = (dxf?.entities ?? []).map((e: any): DxfEntity => {
    const colorHex = resolveColor(e);
    switch (e.type) {
      case 'LINE':
        return { type: 'LINE', vertices: [e.vertices[0], e.vertices[1]], colorHex } as DxfLine;
      case 'LWPOLYLINE':
      case 'POLYLINE':
        return { type: e.type, vertices: e.vertices ?? [], shape: e.shape ?? false, colorHex } as DxfPolyline;
      case 'CIRCLE':
        return { type: 'CIRCLE', center: e.center, radius: e.radius, colorHex } as DxfCircle;
      case 'ARC':
        return { type: 'ARC', center: e.center, radius: e.radius, startAngle: e.startAngle, endAngle: e.endAngle, colorHex } as DxfArc;
      case 'SPLINE':
        return { type: 'SPLINE', controlPoints: e.controlPoints ?? [], closed: e.closed, colorHex } as DxfSpline;
      default:
        return { type: e.type };
    }
  });

  const bounds = computeBounds(entities);
  const w = bounds.maxX - bounds.minX;
  const h = bounds.maxY - bounds.minY;
  const strokeW = Math.max(w, h) * 0.002;

  // Group entities by colorHex (or '#000000' for ByLayer/no color)
  const buckets = new Map<string, string[]>();
  const order: string[] = [];
  for (const e of entities) {
    const colorHex = e.colorHex ?? '#000000';
    if (isNearWhite(colorHex)) continue;
    const svg = entityToSvg(e, bounds, strokeW);
    if (!svg) continue;
    if (!buckets.has(colorHex)) {
      buckets.set(colorHex, []);
      order.push(colorHex);
    }
    buckets.get(colorHex)!.push(svg);
  }

  const layers: Layer[] = order.map(colorHex => ({
    colorHex,
    svgFragment: buckets.get(colorHex)!.join('\n'),
  }));

  const viewBoxOriginal = `0 0 ${w} ${h}`;

  // Trim away whitespace around the actual content; same approach as parseSvg.
  const initialSvg = combineLayers(layers, viewBoxOriginal, w, h);
  const trimmed = await computeTrimmedViewBox(initialSvg, w, h);

  return {
    svgString: combineLayers(layers, trimmed.viewBox, trimmed.naturalWidth, trimmed.naturalHeight),
    layers,
    naturalWidth: trimmed.naturalWidth,
    naturalHeight: trimmed.naturalHeight,
    viewBox: trimmed.viewBox,
    fileName: file.name,
    fileType: 'dxf',
    detectedColors: order,
  };
}

export async function parseVectorFile(file: File): Promise<VectorData> {
  const ext = file.name.split('.').pop()?.toLowerCase();
  if (ext === 'svg') return parseSvg(file);
  if (ext === 'dxf') return parseDxf(file);
  throw new Error(`Unsupported file type: .${ext}. Please upload SVG or DXF files.`);
}
